### ISSUE TITLE
When trying to run netflix conductor docker with postgres, getting this exception

### ISSUE THREAD

**Issue by hchepey-clari** [Netflix/conductor-community#83]
**Describe the bug**
I got the latest version of the conductor repo synced in my local machine. I ran the docker build and then compose up command with postgres persistence.

docker-compose -f docker-compose.yaml -f docker-compose-postgres.yaml up

I am getting this error.

docker-conductor-server-1 |
docker-conductor-server-1 | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
docker-conductor-server-1 | 5328 [main] ERROR org.springframework.boot.SpringApplication [] - Application run failed
docker-conductor-server-1 | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowResource' defined in URL [jar:file:/app/libs/conductor-server-3.11.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-rest-3.11.0-SNAPSHOT.jar!/com/netflix/conductor/rest/controllers/WorkflowResource.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowServiceImpl' defined in URL [jar:file:/app/libs/conductor-server-3.11.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.11.0-SNAPSHOT.jar!/com/netflix/conductor/service/WorkflowServiceImpl.class]:

**Details**
Conductor version:
Persistence implementation:Postgres,
Queue implementation: Dynoqueues
Lock: Redis or Zookeeper?
Workflow definition:
Task definition:
Event handler definition:

**To Reproduce**
1) Get the main branch of the conductor synced on the local machine.
2) Add this dependency in the build.gradle of the conductor
_runtimeOnly group: 'com.netflix.conductor', name: 'conductor-postgres-persistence', version: '3.10.0'_
3) Run docker-compose build and up using the following command
_docker-compose -f docker-compose.yaml -f docker-compose-postgres.yaml up_

**Expected behavior**
Conductor should be up with postgres as persistence.

**Screenshots**
Adding the stacktrace here

docker-conductor-server-1 |
docker-conductor-server-1 | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
docker-conductor-server-1 | 5328 [main] ERROR org.springframework.boot.SpringApplication [] - Application run failed
docker-conductor-server-1 | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowResource' defined in URL [jar:file:/app/libs/conductor-server-3.11.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-rest-3.11.0-SNAPSHOT.jar!/com/netflix/conductor/rest/controllers/WorkflowResource.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowServiceImpl' defined in URL [jar:file:/app/libs/conductor-server-3.11.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.11.0-SNAPSHOT.jar!/com/netflix/conductor/service/WorkflowServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowExecutor' defined in URL [jar:file:/app/libs/conductor-server-3.11.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.11.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/WorkflowExecutor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'deciderService' defined in URL [jar:file:/app/libs/conductor-server-3.11.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.11.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/DeciderService.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'postgresMetadataDAO' defined in class path resource [com/netflix/conductor/postgres/config/PostgresConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.conductor.postgres.dao.PostgresMetadataDAO]: Factory method 'postgresMetadataDAO' threw exception; nested exception is java.lang.NoClassDefFoundError: com/netflix/conductor/core/exception/ApplicationException
docker-conductor-server-1 | at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1 | at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1 | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1 | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1 | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1 | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1 | at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1 | at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1 | at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1 | at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1 | at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1 | at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.19.jar!/:5.3.19]
docker-conductor-server-1 | at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.19.jar!/:5.3.19]
docker-conductor-server-1 | at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.7.jar!/:2.6.7]
docker-conductor-server-1 | at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) [spring-boot-2.6.7.jar!/:2.6.7]
docker-conductor-server-1 | at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) [spring-boot-2.6.7.jar!/:2.6.7]
docker-conductor-server-1 | at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-2.6.7.jar!/:2.6.7]
docker-conductor-server-1 | at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) [spring-boot-2.6.7.jar!/:2.6.7]
docker-conductor-server-1 | at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) [spring-boot-2.6.7.jar!/:2.6.7]
docker-conductor-server-1 | at com.netflix.conductor.Conductor.main(Conductor.java:37) [classes!/:3.11.0-SNAPSHOT]
docker-conductor-server-1 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
docker-conductor-server-1 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
docker-conductor-server-1 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
docker-conductor-server-1 | at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
docker-conductor-server-1 | at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [conductor-server-3.11.0-SNAPSHOT-boot.jar:3.11.0-SNAPSHOT]
docker-conductor-server-1 | at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [conductor-server-3.11.0-SNAPSHOT-boot.jar:3.11.0-SNAPSHOT]
docker-conductor-server-1 | at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [conductor-server-3.11.0-SNAPSHOT-boot.jar:3.11.0-SNAPSHOT]
docker-conductor-server-1 | at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [conductor-server-3.11.0-SNAPSHOT-boot.jar:3.11.0-SNAPSHOT]
docker-conductor-server-1 | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowServiceImpl' defined in URL [jar:file:/app/libs/conductor-server-3.11.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.11.0-SNAPSHOT.jar!/com/netflix/conductor/service/WorkflowServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowExecutor' defined in URL [jar:file:/app/libs/conductor-server-3.11.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.11.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/WorkflowExecutor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'deciderService' defined in URL [jar:file:/app/libs/conductor-server-3.11.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.11.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/DeciderService.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'postgresMetadataDAO' defined in class path resource [com/netflix/conductor/postgres/config/PostgresConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.conductor.postgres.dao.PostgresMetadataDAO]: Factory method 'postgresMetadataDAO' threw exception; nested exception is java.lang.NoClassDefFoundError: com/netflix/conductor/core/exception/ApplicationException
docker-conductor-server-1 | at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1 | at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.19.jar!/:5.3.19]

**Additional context**

I can see that tables are created in the postgres schema but conductor is erroring out after that because of this error.

**Comment by matteius** [comment]
I have just run into this same issue.  Is there a known way to get this working with a prior version?

**Comment by matteius** [comment]
I had to add this file back to the code base and was able to get it to work:  https://raw.githubusercontent.com/Netflix/conductor/v3.9.1-rc.1/core/src/main/java/com/netflix/conductor/core/exception/ApplicationException.java

**Comment by lianjunwei** [comment]
> I had to add this file back to the code base and was able to get it to work: https://raw.githubusercontent.com/Netflix/conductor/v3.9.1-rc.1/core/src/main/java/com/netflix/conductor/core/exception/ApplicationException.java

Great, it solves my problem.

**Comment by hchepey-clari** [comment]
I am getting this error when i am trying to run conductor docker for the version v3.9.1

 36904 [main] WARN  org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext [] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowResource' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-rest-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/rest/controllers/WorkflowResource.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowServiceImpl' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/service/WorkflowServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowExecutor' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/WorkflowExecutor.class]: Unsatisfied dependency expressed through constructor parameter 5; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'executionDAOFacade' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/core/dal/ExecutionDAOFacade.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'es6IndexRestDAO': Invocation of init method failed; nested exception is org.elasticsearch.client.ResponseException: method [GET], host [http://es:9200], URI [/_cluster/health?timeout=30s&wait_for_status=green], status line [HTTP/1.1 408 Request Timeout]
docker-conductor-server-1  | {"cluster_name":"docker-cluster","status":"yellow","timed_out":true,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":25,"active_shards":25,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":25,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":50.0}
docker-conductor-server-1  | 36906 [main] INFO  com.zaxxer.hikari.HikariDataSource [] - HikariPool-1 - Shutdown initiated...
docker-conductor-server-1  | 36912 [main] INFO  com.zaxxer.hikari.HikariDataSource [] - HikariPool-1 - Shutdown completed.
docker-conductor-server-1  | 36916 [main] INFO  org.apache.catalina.core.StandardService [] - Stopping service [Tomcat]
docker-conductor-server-1  | 36936 [main] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener [] - 
docker-conductor-server-1  | 
docker-conductor-server-1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
docker-conductor-server-1  | 36963 [main] ERROR org.springframework.boot.SpringApplication [] - Application run failed
docker-conductor-server-1  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowResource' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-rest-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/rest/controllers/WorkflowResource.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowServiceImpl' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/service/WorkflowServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowExecutor' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/WorkflowExecutor.class]: Unsatisfied dependency expressed through constructor parameter 5; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'executionDAOFacade' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/core/dal/ExecutionDAOFacade.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'es6IndexRestDAO': Invocation of init method failed; nested exception is org.elasticsearch.client.ResponseException: method [GET], host [http://es:9200], URI [/_cluster/health?timeout=30s&wait_for_status=green], status line [HTTP/1.1 408 Request Timeout]
docker-conductor-server-1  | {"cluster_name":"docker-cluster","status":"yellow","timed_out":true,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":25,"active_shards":25,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":25,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":50.0}
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.19.jar!/:5.3.19]

**Comment by hchepey-clari** [comment]
> I had to add this file back to the code base and was able to get it to work: https://raw.githubusercontent.com/Netflix/conductor/v3.9.1-rc.1/core/src/main/java/com/netflix/conductor/core/exception/ApplicationException.java

ApplicationException.java is there in 3.9.1 version... But still I am getting the same error.

**Comment by hchepey-clari** [comment]
> I am getting this error when i am trying to run conductor docker for the version v3.9.1
> 
> 36904 [main] WARN org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext [] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowResource' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-rest-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/rest/controllers/WorkflowResource.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowServiceImpl' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/service/WorkflowServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowExecutor' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/WorkflowExecutor.class]: Unsatisfied dependency expressed through constructor parameter 5; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'executionDAOFacade' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/core/dal/ExecutionDAOFacade.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'es6IndexRestDAO': Invocation of init method failed; nested exception is org.elasticsearch.client.ResponseException: method [GET], host [http://es:9200], URI [/_cluster/health?timeout=30s&wait_for_status=green], status line [HTTP/1.1 408 Request Timeout] docker-conductor-server-1 | {"cluster_name":"docker-cluster","status":"yellow","timed_out":true,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":25,"active_shards":25,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":25,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":50.0} docker-conductor-server-1 | 36906 [main] INFO com.zaxxer.hikari.HikariDataSource [] - HikariPool-1 - Shutdown initiated... docker-conductor-server-1 | 36912 [main] INFO com.zaxxer.hikari.HikariDataSource [] - HikariPool-1 - Shutdown completed. docker-conductor-server-1 | 36916 [main] INFO org.apache.catalina.core.StandardService [] - Stopping service [Tomcat] docker-conductor-server-1 | 36936 [main] INFO org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener [] - docker-conductor-server-1 | docker-conductor-server-1 | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. docker-conductor-server-1 | 36963 [main] ERROR org.springframework.boot.SpringApplication [] - Application run failed docker-conductor-server-1 | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowResource' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-rest-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/rest/controllers/WorkflowResource.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowServiceImpl' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/service/WorkflowServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowExecutor' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/WorkflowExecutor.class]: Unsatisfied dependency expressed through constructor parameter 5; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'executionDAOFacade' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/core/dal/ExecutionDAOFacade.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'es6IndexRestDAO': Invocation of init method failed; nested exception is org.elasticsearch.client.ResponseException: method [GET], host [http://es:9200], URI [/_cluster/health?timeout=30s&wait_for_status=green], status line [HTTP/1.1 408 Request Timeout] docker-conductor-server-1 | {"cluster_name":"docker-cluster","status":"yellow","timed_out":true,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":25,"active_shards":25,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":25,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":50.0} docker-conductor-server-1 | at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.19.jar!/:5.3.19] docker-conductor-server-1 | at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.19.jar!/:5.3.19] docker-conductor-server-1 | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.19.jar!/:5.3.19]

Looks like that es6 docker instance is somehow not reachable. 

And most weird part is that it worked yesterday. I was able to create TasksDefs and WorkflowDefs in the Postgres. Not sure what could possibly go wrong without any changes I made,  changes are the same as of yesterday.

**Comment by yuri1969** [comment]
The Conductor server waits for the ES cluster to get ready and shuts down if it times out. It can be seen it the log it simply waited 30 sec on `GET /_cluster/health?timeout=30s&wait_for_status=green` and then failed since the returned ES cluster status was still _yellow_ due to the default Docker ES setup.

The server can be set to expect the _yellow_ status via `conductor.elasticsearch.clusterHealthColor=yellow` as described at [Elasticsearch timeout](https://conductor.netflix.com/gettingstarted/docker.html) section of the documentation.
